services:
  api:
    build: .
    container_name: house_api
    env_file:
      - .env.local
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - house-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    container_name: house_db
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - house-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: house_rabbitmq
    env_file:
      - .env.local
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - house-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: .
    container_name: house_worker
    env_file:
      - .env.local
    environment:
      - RUN_MODE=worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - house-network
    volumes:
      - .:/app

  redis:
    image: redis:7.2-alpine
    container_name: house_redis
    ports:
      - "6379:6379"
    networks:
      - house-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  house-network:
    driver: bridge

volumes:
  postgres_data: