version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
    environment:
      - DATABASE_URL=sqlite:///./healthcare_app.db
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-super-secret-key}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite:///./healthcare_app.db
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A app.tasks.worker worker --loglevel=info